name: MobArenaGod
main: com.ACStache.MobArenaGod.MobArenaGod
version: 0.4
author: ACStache
description: A simple God Mode plugin that plays nice with Mob Arena
softdepend: [MobArena]
commands:
    mag:
        description: Turn god mode on or off, or check the status
        usage: |
               /mag
               /mag status
               /mag reload
permissions:
    MobArenaGod.toggle:
        description: allows use of "/mag" command to toggle god mode
        default: op
    MobArenaGod.status:
        description: allows use of "/mag status" command to check current god mode status
        default: op
    MobArenaGod.reload:
        description: allows use of "/mag reload" command to reload the config
        default: op