name: ArenaGodPlus
main: com.ACStache.ArenaGodPlus.ArenaGodPlus
version: 0.6-Dev
author: ACStache
description: A simple God Mode plugin that plays nice with Mob Arena & PVP Arena
softdepend: [MobArena, pvparena]
commands:
    god:
        description: Turn god mode on or off, or check the status
        usage: |
               /god
               /god status
               /god reload
    agp:
        description: Alias of /god
        usage: |
               /agp
               /agp status
               /agp reload
permissions:
    ArenaGodPlus.toggle:
        description: allows use of "/god" command to toggle god mode
        default: op
    ArenaGodPlus.status:
        description: allows use of "/god status" command to check current god mode status
        default: op
    ArenaGodPlus.reload:
        description: allows use of "/god reload" command to reload the config
        default: op