name: ArenaGod+
main: com.ACStache.ArenaGodPlus.ArenaGodPlus
version: 0.5-Dev
author: ACStache
description: A simple God Mode plugin that plays nice with Mob Arena & PVP Arena
softdepend: [MobArena, pvparena]
commands:
    god:
        description: Turn god mode on or off, or check the status
        usage: |
               /god
               /god status
               /god reload
permissions:
    ArenaGod+.toggle:
        description: allows use of "/god" command to toggle god mode
        default: op
    ArenaGod+.status:
        description: allows use of "/god status" command to check current god mode status
        default: op
    ArenaGod+.reload:
        description: allows use of "/god reload" command to reload the config
        default: op