name: ArenaGodPlus
main: com.ACStache.ArenaGodPlus.ArenaGodPlus
version: 0.7
author: ACStache
description: A simple God Mode plugin that plays nice with Mob Arena & PVP Arena
softdepend: [Heroes, MobArena, MobDungeon, pvparena, War]
commands:
    god:
        description: Turn god mode on or off, or check the status
        usage: |
               /god
               /god status
               /god reload
               /god give playername
    agp:
        description: Alias of /god
        usage: |
               /agp
               /agp status
               /agp reload
               /agp give playername
permissions:
    ArenaGodPlus.toggle:
        description: Ability to toggle personal God Mode
        default: op
    ArenaGodPlus.give:
        description: Ability to toggle other player's God Mode
        default: op
    ArenaGodPlus.status:
        description: Ability to check current God Mode state
        default: op
    ArenaGodPlus.reload:
        description: Ability to reload the config file
        default: op